### ISSUE TITLE
运行cyber_example_listener和cyber_example_talker没有任何打印可能是什么问题

### ISSUE THREAD

**Issue by Yoke365** [zhxt/cyber-rt#5]
![image](https://user-images.githubusercontent.com/45156993/103274913-d12ef080-49fd-11eb-90aa-b8796e38ad44.png)

**Comment by dingjiangang** [comment]
微信 13052288554

**Comment by dingjiangang** [comment]
> ![image](https://user-images.githubusercontent.com/45156993/103274913-d12ef080-49fd-11eb-90aa-b8796e38ad44.png)

cyber安装到了/usr/local/opt下面，要添加环境变量，执行即可
